### PR TITLE
Use Browserify to build output bundle

### PR DESCRIPTION
**Pull request by bendrucker**
Eliminates a bunch of gulp code in favor of CLI build scripts. Also allows a user to `require('angular-immutable')` and get back `'immutable'` for easier dependency listing. 

I haven't committed any built files here. You'll do that with `npm run build`.

### CODE REVIEW

**Comment by mgechev** [comment]
Great, looks beautiful! The `dist` directory already contains the latest build. I'm pushing the built files as well because the module is also published in bower.

**Comment by mgechev** [comment]
Actually I'm going to add a [postinstall hook](https://github.com/bower/bower/blob/master/HOOKS.md) for bower.

**Comment by bendrucker** [comment]
Hang on! Bower hooks actually don't do what you think. Bower hooks are only for the user and won't be run from inside installed packages.

**Comment by bendrucker** [comment]
Scripts are an inherent vulnerability (https://blog.liftsecurity.io/2015/01/27/a-malicious-module-on-npm) and Bower chose not to implement them. This is actually somewhat reasonable. npm user-side scripts (versus a maintainer-side one like prepublish) are there for things like OS or version specific compilation and transpiling JS lazily is an anti-pattern. Since Bower isn't pointing at anything with native code there's no reason for scripts and it's more important to protect users.

The problem with Bower plus a build process is that Bower doesn't actually host code the way npm does.

**Comment by mgechev** [comment]
Yeah, just read the docs. It seems `dist` is going to live. Thanks! :-)

**Comment by bendrucker** [comment]
I do have a way of getting around that:

http://github.com/bendrucker/publicist

Have been using it for a while and will document it better for general use soon.

**Pull request merged**
